travis:
  secure:
    BINSTAR_TOKEN: H0g0V8QfK8V0tnWplVqn2e1ZQx7pBIa3BJc+rMazNkCVl33b2swSHnQC90qMvoYnMbI2MzzRKS2G1ou8/J0EzsJPVms+7fqSNeyz3s9nSEpPel59H8wb7UQ1cE3B4aB0DY2PHBSobwplF2USRMX2y9dkXxlr0TvFRq/KBaEygdZvuKTgTmwpy4MFMevnizEXbn/pCm/dEVZC0Y9SIMFnhHMbzIwZBLOmPW6Xq0eKwI56xZyLuLo5cxtKBoBvdEe0L82G+fesUtSN2S/DRsJNqa366+jLfCoj/pWzZSzCuw9Dnl7I0oxKDn0oYYGfeh4Afcp76lu59JLVucuW7BRmeFy6CbPMf/eT/Sfzhu8fu0sOX5cmJXMmMtJoWVWppSRUqTlT4BCDy5R5KDknl4Hq+QKnjq70CaPbSVCTTCbn9phDrj3KkZo+DGQV4avPihhiyvTMYuZSMaouJCH6w9I/Cvw4bnHRdjz5E/SLy+8Yl5f4WuD9JLEVQdLmgB7VQcvR0auRlGdZm0UrmxPzL1X/t0/N7DTkYoH43khyzOPhdn2hvqjqVJ3OeeEZ4/HPDYY3TLlctgnsgqEiRdPeUWCbMfn+o+rc1oVs2r46w/A5uk/zwdlFp49JraJJKTdC+TedfXtTp29LU5nxR7YV0jYbdDzCthVHGJn9uIQ+DzfxbrU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
